# Generated by Django 5.0.6 on 2025-04-30 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True)),
                ('validade_inicio', models.DateTimeField()),
                ('validade_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('E', 'Expirado'), ('R', 'Revogado')], default='A', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'qrcode',
            },
        ),
    ]
