# Generated by Django 5.0.6 on 2025-05-02 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0002_qrcode_ambiente'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='usuario',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='criado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes_criados', to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QrCodeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_permitidos', to='qrcode.qrcode')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes_permitidos', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'qrcode_usuarios',
                'unique_together': {('qrcode', 'usuario')},
            },
        ),
    ]
