# Generated by Django 5.0.6 on 2025-06-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0003_remove_qrcode_usuario_qrcode_criado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
