# Generated by Django 5.0.6 on 2025-04-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('A', 'Administrador'), ('F', 'Funcionário'), ('H', 'Hóspede'), ('U', 'Usuário')], max_length=20)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
